//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در این تاریخ برای این پرسنل اطلاعات حقوقی وجود دارد..
        /// </summary>
        public static string Conflict {
            get {
                return ResourceManager.GetString("Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت استرینگ ارسال شده بر اساس {0} نادرست می‌باشد.
        /// </summary>
        public static string DataNotInFormat {
            get {
                return ResourceManager.GetString("DataNotInFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با خطا مواجه شد..
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار پارامتر {0} نمی‌تواند خالی باشد.
        /// </summary>
        public static string IsNullOrEmpty {
            get {
                return ResourceManager.GetString("IsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول {0} نمی‌تواند بیش از {1} کارکتر باشد.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روش محاسبه نامعتبر است!.
        /// </summary>
        public static string overTimeCalculatorError {
            get {
                return ResourceManager.GetString("overTimeCalculatorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه پرسنل نمی تواند خالی باشد..
        /// </summary>
        public static string PersonEmpty {
            get {
                return ResourceManager.GetString("PersonEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرسنل {0} یافت نشد!.
        /// </summary>
        public static string PersonNotFound {
            get {
                return ResourceManager.GetString("PersonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} الزامی است.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرسنلی با مشخصات {0} یافت نشد!.
        /// </summary>
        public static string SalaryNotFound {
            get {
                return ResourceManager.GetString("SalaryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با موفقیت انجام شد..
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
    }
}
